save: "../save/CFD/"
dt_save: 0.001
ini_time: 0.
fin_time: 0.012
nx: 1024
ny: 1
nz: 1
xL: -1.
xR: 1.
yL: -1.
yR: 1.
zL: -1.
zR: 1.
bc: "trans"
gamma: 1.6666666666666667
eta: 1.e-8
zeta: 1.e-8
CFL: 3.e-1
if_second_order: 1.
if_show: 1
show_steps: 100
init_mode: "shocktube5"
p_floor: 1.e-4
numbers: 10
init_mode_Multi: "1D_shocks"
init_key: 2022
M0: 1.
dk: 1.
dkMx: 1.
