model_name: "PINN"
scenario: "pde1D"
model_update: 500
filename: "1D_Advection_Sols_beta0.1.hdf5"
epochs: 15000
input_ch: 2
output_ch: 1
learning_rate: 1.e-3
root_path: "../data"
val_num: 10
if_periodic_bc: True
period: 5000
val_time: 2.0
val_batch_idx: 10
aux_params: [0.1]
