model_name: "Unet"
if_training: True
continue_training: False
batch_size: 50
unroll_step: 20
t_train: 200
model_update: 1
filename: "1D_Advection_Sols_beta4.0.hdf5"
single_file: True
reduced_resolution: 4
reduced_resolution_t: 5
reduced_batch: 1
epochs: 500
learning_rate: 1.e-3
num_workers: 0
#Unet
in_channels: 1
out_channels: 1
ar_mode: True
pushforward: True
#FNO
num_channels: 1
modes: 12
width: 20
scheduler_step: 100
scheduler_gamma: 0.5
initial_step: 10
