#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho1e0_Nu1e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho1e0_Nu2e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho1e0_Nu5e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho1e0_Nu1e1.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho2e0_Nu1e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho2e0_Nu2e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho2e0_Nu5e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho2e0_Nu1e1.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho5e0_Nu1e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho5e0_Nu2e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho5e0_Nu5e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho5e0_Nu1e1.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho1e1_Nu1e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho1e1_Nu2e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho1e1_Nu5e0.yaml
#CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho1e1_Nu1e1.yaml
CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho1e1_Nu5e-1.yaml
CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho5e0_Nu5e-1.yaml
CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho2e0_Nu5e-1.yaml
CUDA_VISIBLE_DEVICES='3' python3 reaction_diffusion_Hydra.py +args=Rho1e0_Nu5e-1.yaml
